CREATE TABLE ANSWER(
 ANS_NO NUMBER PRIMARY KEY,
 INQ_NO NUMBER NOT NULL REFERENCES INQUIRY(INQ_NO),
 ANS_TITLE VARCHAR2(100) NOT NULL,
 ANS_CONTENT VARCHAR2(1000),
 ANS_DATE DATE DEFAULT SYSDATE
);

DROP TABLE ANSWER;
CREATE SEQUENCE SEQ_ANSWER;
SELECT * FROM ANSWER;

SELECT *FROM FEED;

SELECT * FROM INQUIRY JOIN MEMBER ON INQ_MEMBER=MEMBER_NO WHERE INQ_NO=27