SELECT * FROM REPORT ;
SELECT * FROM member ;

ALTER TABLE REPORT DROP column REPORT_RESOURCE;

SELECT * FROM FEED;

SELECT MEMBER_NO FROM FEED LEFT JOIN MEMBER USING(MEMBER_NO) WHERE FEED_NO = 1387;
SELECT MEMBER_NO FROM FEED LEFT JOIN MEMBER USING(MEMBER_NO) WHERE FEED_NO = ?


INSERT INTO REPORT VALUES(seq_report.NEXTVAL,4,5,'욕설','너무해요',DEFAULT,DEFAULT,NULL);