SELECT * FROM LIKE_FEED WHERE MEMBERno = 2 AND feed_no=1083;
SELECT * FROM FEED ;
SELECT * FROM "MEMBER";
SELECT * FROM LIKE_FEED ;

DELETE LIKE_FEED;

INSERT INTO LIKE_FEED VALUES(2,403,+1);

CREATE TABLE LIKE_feeddsa(
	memberNo NUMBER,
	feed_No NUMBER,
	likes NUMBER,
	likes_switch number(1) DEFAULT 0,
	FOREIGN KEY (memberNo) REFERENCES MEMBER(MEMBER_NO),
	FOREIGN KEY (feed_No) REFERENCES FEED(FEED_NO)
	
);

DROP TABLE LIKE_feeddsa;


SELECT * FROM LIKE_FEED WHERE MEMBERno = 2 AND feed_no=403;
INSERT INTO LIKE_FEED VALUES(2,403,3,1);

ALTER TABLE LIKE_FEED ADD likes_switch NUMBER(1) DEFAULT 0;

DROP TABLE LIKE_feed;
SELECT * FROM LIKE_FEED;
alter session set ddl_lock_timeout = 5;

SELECT * FROM LIKE_FEED LEFT JOIN feed using(feed_no);

SELECT * FROM like_feed a left JOIN feed b ON a.feed_no = b.feed_no;

UPDATE (SELECT * FROM like_feed a left JOIN feed b ON a.feed_no = b.feed_no)
SET CONTENT = '11e122121'
WHERE feed_no= 403;
ALTER TABLE LIKE_FEED DROP COLUMN likes;+

SELECT * FROM LIKE_FEED;
SELECT * FROM FEED;

INSERT INTO LIKE_FEED VALUES(2,403,1);

DELETE like_feed;

DELETE FROM LIKE_FEED WHERE memberno = 3;

CREATE OR REPLACE TRIGGER TR_LIKE_FEED
AFTER INSERT ON LIKE_FEED
FOR EACH ROW
BEGIN
    UPDATE FEED 
    SET LIKES = LIKES + 1
    WHERE feed_no = :NEW.feed_no;
END;
/

CREATE OR REPLACE TRIGGER TR_LIKE_FEED_del
AFTER DELETE ON LIKE_FEED
FOR EACH ROW
BEGIN
    UPDATE FEED 
    SET LIKES = LIKES - 1
    WHERE feed_no = :old.feed_no;
END;
/

UPDATE feed SET likes =0;
SELECT * FROM feed;
SELECT * FROM LIKE_FEED;

DROP TRIGGER TR_LIKE_FEED_del;

ALTER TABLE LIKE_FEED DROP COLUMN likes_switch;
