SELECT * FROM MEMBER m JOIN SUBSCRIBE S USING(MEMBER_NO) JOIN ARTIST_GROUP AG ON S.GROUP_NO =AG.GROUP_NO WHERE MEMBER_NO=9;
SELECT * FROM MEMBER m JOIN SUBSCRIBE S USING(MEMBER_NO) JOIN ARTIST_GROUP AG ON S.GROUP_NO =AG.GROUP_NO JOIN MEMBERSHIP m2 ;

SELECT * FROM SUBSCRIBE;
SELECT * FROM MEMBERSHIP;
SELECT * FROM REPORT;
SELECT * FROM PENALTY;

SELECT MEMBER_ID FROM REPORT RE LEFT JOIN MEMBER ON MEMBER_NO=REPORTED_MEMBER;
SELECT MEMBER_ID FROM REPORT RE LEFT JOIN MEMBER ON MEMBER_NO=REPORTING_MEMBER;
SELECT * FROM (SELECT ROWNUM AS RNUM,RA.* FROM (SELECT RE.*,M.MEMBER_ID AS REPOTED,ML.MEMBER_ID AS REPORTING FROM REPORT RE LEFT JOIN MEMBER M ON M.MEMBER_NO=RE.REPORTED_MEMBER JOIN MEMBER ML ON ML.MEMBER_NO=RE.REPORTING_MEMBER ORDER BY REPORT_DATE DESC)RA) WHERE RNUM BETWEEN 1 AND 10 ;
SELECT ROWNUM AS RNUM,RA.* FROM (SELECT RE.*,M.MEMBER_ID AS REPOTED,ML.MEMBER_ID AS REPORTING FROM REPORT RE LEFT JOIN MEMBER M ON M.MEMBER_NO=RE.REPORTED_MEMBER JOIN MEMBER ML ON ML.MEMBER_NO=RE.REPORTING_MEMBER ORDER BY REPORT_DATE DESC)RA WHERE REPORT_NO=21;

CREATE TABLE PENALTY(
	PENALTY_NO PRIMARY KEY,
	REPORT_NO REFERENCES REPORT(REPORT_NO),
	MEMBER_NO REFERENCES MEMBER(MEMBER_NO),
	PENALTY_CATEGORY CHECK IN('unactive','resign'),
	PENALTY_START_DATE DATE DEFAULT SYSDATE,
	PENALTY_END_DATE DATE
);

CREATE SEQUENCE SEQ_PENALTY;

