CREATE TABLE INQUIRY(
 INQ_NO NUMBER PRIMARY KEY,
 INQ_MEMBER NUMBER NOT NULL REFERENCES MEMBER(MEMBER_NO),
 INQ_TITLE VARCHAR2(100) NOT NULL,
 INQ_CONTENT VARCHAR2(1000),
 INQ_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_INQUIRY;
DROP TABLE INQUIRY;

INSERT INTO INQUIRY VALUES(SEQ_INQUIRY.NEXTVAL,2,'삭제가 하는 방법','GOPJEGPIORGP',DEFAULT);
INSERT INTO INQUIRY VALUES(SEQ_INQUIRY.NEXTVAL,3,'탈퇴가 안 ','gbeafafOafsdaP',DEFAULT);
INSERT INTO INQUIRY VALUES(SEQ_INQUIRY.NEXTVAL,4,'가격이 얼마인가요','굿즈asdasd',DEFAULT);
